// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJy9-l2iIkXAiwST3C9iH8i5a7GB9Xr_A',
    appId: '1:1083494702041:web:5ff2875c9e5a7c2c57d7c8',
    messagingSenderId: '1083494702041',
    projectId: 'fl-chatgpt',
    authDomain: 'fl-chatgpt.firebaseapp.com',
    storageBucket: 'fl-chatgpt.appspot.com',
    measurementId: 'G-23WFVTHEMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzCF6IHR_ZvytLb85NSVzxvkLhhjxSs3A',
    appId: '1:1083494702041:android:a59465639b79be2f57d7c8',
    messagingSenderId: '1083494702041',
    projectId: 'fl-chatgpt',
    storageBucket: 'fl-chatgpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWonle48teHgh2mril1Ew-QV5wHvTRAbs',
    appId: '1:1083494702041:ios:6750f638a8f501ac57d7c8',
    messagingSenderId: '1083494702041',
    projectId: 'fl-chatgpt',
    storageBucket: 'fl-chatgpt.appspot.com',
    iosClientId: '1083494702041-ag3vqc5hvvvfap7ojq5n1k4pi2goe8gu.apps.googleusercontent.com',
    iosBundleId: 'com.iqfareez.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWonle48teHgh2mril1Ew-QV5wHvTRAbs',
    appId: '1:1083494702041:ios:6750f638a8f501ac57d7c8',
    messagingSenderId: '1083494702041',
    projectId: 'fl-chatgpt',
    storageBucket: 'fl-chatgpt.appspot.com',
    iosClientId: '1083494702041-ag3vqc5hvvvfap7ojq5n1k4pi2goe8gu.apps.googleusercontent.com',
    iosBundleId: 'com.iqfareez.appChat',
  );
}
